MY_APPS = reflector
MY_OTHER = us_config_fm0_sgmii.xml us_config_serdes_0xe_2sgmii.xml \
	us_policy_hash_ipv4_src_dst.xml

MY_CFLAGS := -I$(TOP_LEVEL)/apps/include

reflector_objs := main.o
reflector_link_libs := apps_badinit usdpaa_qman usdpaa_bman usdpaa_fman usdpaa_shmem usdpaa_of
reflector_sys_link_libs := pthread
