obj-$(CONFIG_FSL_BMAN_CONFIG)	+= bman_config.o
obj-$(CONFIG_FSL_BMAN_PORTAL)	+= bman_driver.o bman_low.o bman_high.o
obj-$(CONFIG_FSL_BMAN_TEST)	+= bman_tester.o
bman_tester-y			 = bman_test.o bman_test_high.o bman_test_low.o
