bin_PROGRAMS = qbman_speed

my_CFLAGS := -I$(TOP_LEVEL)/apps/include

qbman_speed_SOURCES := main.c speed.c blastman.c
qbman_speed_LDADD := apps_badinit usdpaa_qbman usdpaa_shmem
qbman_speed_sys_LDADD := pthread
